name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 12 hours
    - cron: "0 */8 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          SHOW_TITLE: true
          TIME_RANGE: last_30_days
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
